# Generated by Django 5.1.6 on 2025-03-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_interestscategory_language_requiredrole_and_more'),
        ('users', '0010_profile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='projects.category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='users', to='projects.skill'),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
