# Generated by Django 4.2.18 on 2025-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_profile_interests_profile_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_online",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
