# Generated by Django 4.2.18 on 2025-01-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_remove_researchproject_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchproject",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="research_projects/"
            ),
        ),
    ]
