# Generated by Django 4.2.18 on 2025-01-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_researchproject_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="researchproject",
            name="availability",
            field=models.CharField(
                choices=[("free", "Free"), ("restricted", "Restricted")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="partial_access_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
