# Generated by Django 4.2.18 on 2025-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_alter_researchproject_availability_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="text_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="availability",
            field=models.CharField(
                choices=[("free", "Free"), ("restricted", "Restricted")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="comments",
            field=models.TextField(
                blank=True, default="No comments available.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="description",
            field=models.TextField(default="No description available."),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="partial_access_description",
            field=models.TextField(
                blank=True, default="No partial access description.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="researchproject",
            name="title",
            field=models.CharField(default="Untitled Project", max_length=200),
        ),
    ]
