# Generated by Django 4.2.18 on 2025-01-28 16:00

from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0006_citation_comment_project_tag_delete_researchproject_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
