# Generated by Django 4.2.18 on 2025-01-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_projectsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_sections",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProjectSection",
        ),
    ]
