# Generated by Django 4.2.18 on 2025-02-12 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0009_projectapplication_remove_comment_project_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Research Project",
                "verbose_name_plural": "Research Projects",
            },
        ),
        migrations.AlterModelOptions(
            name="projectapplication",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "Project Application",
                "verbose_name_plural": "Project Applications",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="message",
            field=models.TextField(
                blank=True, help_text="Optional message to the project owner"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                default=projects.models.get_default_owner,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="skills_required",
            field=models.CharField(
                default="No specific skills required",
                help_text="Comma-separated list of skills",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="projectapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
