# Generated by Django 4.2.18 on 2025-02-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
