# Generated by Django 4.2.18 on 2025-02-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_chatroom_chatmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.ManyToManyField(blank=True, to="projects.category"),
        ),
    ]
