# Generated by Django 4.2.18 on 2025-02-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_category_remove_project_category_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_mission",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_objectives",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="required_roles",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
