# Generated by Django 4.2.18 on 2025-02-22 08:23

from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_project_languages_project_project_mission_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SkillsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(
                default="No description provided",
                validators=[projects.models.MaxWordsValidator(250)],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_mission",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[projects.models.MaxWordsValidator(70)],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_objectives",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[projects.models.MaxWordsValidator(150)],
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="skills_required",
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                default="Untitled Project",
                max_length=200,
                validators=[projects.models.MaxWordsValidator(20)],
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "skills_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="projects.skillscategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "interests_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interests",
                        to="projects.interestscategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="skills_required",
            field=models.ManyToManyField(
                blank=True, help_text="Select required skills", to="projects.skill"
            ),
        ),
    ]
