# Generated by Django 5.1.6 on 2025-03-01 04:09

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_languages_project_project_mission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='RequiredRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Required Role',
                'verbose_name_plural': 'Required Roles',
            },
        ),
        migrations.CreateModel(
            name='SkillsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='application_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of applications received for this project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the project page has been viewed.'),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='contribution',
            field=models.TextField(blank=True, help_text='Опишите, как вы планируете участвовать в проекте.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', validators=[projects.models.MaxWordsValidator(250)]),
        ),
        migrations.RemoveField(
            model_name='project',
            name='languages',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_mission',
            field=models.TextField(blank=True, null=True, validators=[projects.models.MaxWordsValidator(70)]),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_objectives',
            field=models.TextField(blank=True, null=True, validators=[projects.models.MaxWordsValidator(150)]),
        ),
        migrations.RemoveField(
            model_name='project',
            name='required_roles',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills_required',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=200, validators=[projects.models.MaxWordsValidator(20)]),
        ),
        migrations.CreateModel(
            name='ChatFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chats', models.ManyToManyField(blank=True, related_name='folders', to='projects.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_folders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='projects.interestscategory')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='projects.interestssubcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SkillsSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='projects.skillscategory')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='projects.skillssubcategory')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Select languages relevant to the project (e.g., Python, Spanish, etc.)', to='projects.language'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_roles',
            field=models.ManyToManyField(blank=True, help_text='Select roles required for the project (e.g., Designer, Developer, etc.)', to='projects.requiredrole'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills_required',
            field=models.ManyToManyField(blank=True, help_text='Select required skills', to='projects.skill'),
        ),
        migrations.CreateModel(
            name='FavoriteProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
