# Generated by Django 4.2.18 on 2025-02-22 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_interestscategory_skillscategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="interests_category",
        ),
        migrations.RemoveField(
            model_name="skill",
            name="skills_category",
        ),
        migrations.AddField(
            model_name="projectapplication",
            name="contribution",
            field=models.TextField(
                blank=True,
                help_text="Опишите, как вы планируете участвовать в проекте.",
            ),
        ),
        migrations.CreateModel(
            name="SkillsSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="projects.skillscategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
        migrations.CreateModel(
            name="InterestsSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="projects.interestscategory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "category")},
            },
        ),
        migrations.AddField(
            model_name="interest",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="projects.interestssubcategory",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="skill",
            name="subcategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                to="projects.skillssubcategory",
            ),
            preserve_default=False,
        ),
    ]
