# Generated by Django 4.2.18 on 2025-02-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_alter_project_description_alter_project_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.CreateModel(
            name="RequiredRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Required Role",
                "verbose_name_plural": "Required Roles",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="application_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of applications received for this project."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times the project page has been viewed."
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="project",
            name="required_roles",
        ),
        migrations.AddField(
            model_name="project",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select languages relevant to the project (e.g., Python, Spanish, etc.)",
                to="projects.language",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="required_roles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select roles required for the project (e.g., Designer, Developer, etc.)",
                to="projects.requiredrole",
            ),
        ),
    ]
